### ISSUE TITLE
Inexistent endpoint in PlayerController.

### ISSUE THREAD

**Issue by sadaakisz** [cjmazzarri/TeamMatch_Microservices#34]
PlayerController:71 makes reference to unknown endpoint.

```
@GetMapping("/profile/{id}")
    public ResponseEntity<Profile> getProfileByUserId(@PathVariable(name = "id") Long id) {
        return playerService.getProfile(id);
    }
```

As-is, incorrect: ```/api/profile/{id}```

Correct endpoint: ```/api/players/{id}/profiles```

**Comment by TheRoro** [comment]
🐛 Fixed bug, thank you for your feedback!
